spring.application.name=MediGo

# Base de datos — Supabase Connection Pooler (credenciales via variables de entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.njsemkjclsyfilecvgat}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
test.value=prod


# JPA
spring.jpa.show-sql=true

# Liquibase — desactivado por ahora (ya creamos las tablas manual)
spring.liquibase.enabled=false

# Redis (lo conectamos después)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Puerto
server.port=8080